FROM archlinux

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm \
    gcc clang make automake autoconf libtool pkg-config \
    libsndfile fftw autoconf-archive qt5-base libao wget \
    jack2 cairo git python3 python-scipy ccache meson lv2 lilv

ADD . /spectmorph
WORKDIR /spectmorph
