#!/bin/bash

source ./config.sh

SETUP_NSI="setup-spectmorph.nsi"
echo "; $SETUP_NSI (generated by mk-setup.sh)" > $SETUP_NSI

cat >> $SETUP_NSI << EOH
; Compress better (and slower)
SetCompressor /SOLID /FINAL lzma

;--------------------------------
!include MUI2.nsh
!include x64.nsh
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

Var pluginDir

; The name of the installer
Name "SpectMorph ${PACKAGE_VERSION}"
; The file to write
OutFile "setup-spectmorph-${PACKAGE_VERSION}.exe"

; License
!insertmacro MUI_PAGE_LICENSE "COPYING.GPL3"

; The default installation directory
InstallDir "\$PROGRAMFILES64\\SpectMorph"

; Directory page for the VST Plugin
!define MUI_DIRECTORYPAGE_TEXT_TOP \\
"Setup will install the SpectMorph 64 bit VST plugin. Please select the VST path to your preferred DAW software."
!define MUI_DIRECTORYPAGE_TEXT_DESTINATION \\
"Choose the folder in which to the VST Plugin."
!define MUI_DIRECTORYPAGE_VARIABLE \$pluginDir
!insertmacro MUI_PAGE_DIRECTORY

; Directory page for SpectMorph
!define MUI_DIRECTORYPAGE_TEXT_TOP \\
"The SpectMorph plugin requires additional Data and Program Files."
!define MUI_DIRECTORYPAGE_TEXT_DESTINATION \\
"Choose the folder in which to install Data and Program Files."
!insertmacro MUI_PAGE_DIRECTORY

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; Finish page
!define MUI_FINISHPAGE_TITLE "Welcome to SpectMorph"
!define MUI_FINISHPAGE_TEXT "SpectMorph is installed in\$\\r\$\\n\$\\r\$\\n\$pluginDir\$\\r\$\\n\$\\r\$\\nnow."
!define MUI_FINISHPAGE_LINK "SpectMorph Homepage"
!define MUI_FINISHPAGE_LINK_LOCATION "http://www.spectmorph.org"
!define MUI_FINISHPAGE_NOREBOOTSUPPORT
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

Function .onInit
  ClearErrors
  StrCpy \$pluginDir "\$PROGRAMFILES64\\Steinberg\\VstPlugins"
FunctionEnd

;--------------------------------
; The stuff to install
Section "Install" ;No components page, name is not important
EOH

(
  OUT_PATH="_none_"
  find instruments templates fonts -type f | while read FILE
  do
    NEW_OUT_PATH="$(dirname $FILE)"
    if test "x$NEW_OUT_PATH" != "x$OUT_PATH"; then
      OUT_PATH="$NEW_OUT_PATH"
      echo "  SetOutPath \$INSTDIR/$OUT_PATH" | sed 's,/,\\,g'
    fi
    echo "  File $FILE" | sed 's,/,\\,g'
  done
) >> $SETUP_NSI

cat >> $SETUP_NSI << EOH
  SetOutPath \$pluginDir
  File SpectMorph.dll
  File SpectMorph.clap
  CreateShortCut "\$pluginDir\\SpectMorph.data.lnk" "\$INSTDIR"

  WriteUninstaller "\$INSTDIR\\Uninstall.exe"

  Call StorePluginDir

  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SpectMorph" "DisplayName" "SpectMorph ${PACKAGE_VERSION}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SpectMorph" "UninstallString" '"\$INSTDIR\\uninstall.exe"'
  WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SpectMorph" "NoModify" 1
  WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SpectMorph" "NoRepair" 1
SectionEnd

;--------------------------------
;Uninstaller Section

Section "Uninstall"
  DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\SpectMorph"

  Call un.LoadPluginDir
EOH

(
  # remove files
  find instruments templates fonts -type f | while read FILE
  do
    echo "  Delete \$INSTDIR/$FILE" | sed 's,/,\\,g'
  done

  # remove dirs in reverse order
  find instruments templates fonts -type d | tac | while read DIR
  do
    echo "  RMDir \$INSTDIR/$DIR" | sed 's,/,\\,g'
  done
) >> $SETUP_NSI

cat >> $SETUP_NSI << EOH
  Delete "\$INSTDIR\\Uninstall.exe"
  Delete "\$INSTDIR\\PluginDir.txt"
  RMDir "\$INSTDIR"
  Delete "\$pluginDir\\SpectMorph.dll"
  Delete "\$pluginDir\\SpectMorph.clap"
  Delete "\$pluginDir\\SpectMorph.data.lnk"
SectionEnd

; uninstall needs to know in which vst plugin dir SpectMorph.dll was installed
;
; we store that information in a text file during install and retrieve
; it from there on uninstall
Var filePluginDir

Function StorePluginDir
  FileOpen \$filePluginDir "\$INSTDIR\\PluginDir.txt" w
  FileWrite \$filePluginDir "\$pluginDir"
  FileClose \$filePluginDir
  SetFileAttributes "\$INSTDIR\\PluginDir.txt" HIDDEN
FunctionEnd

Function un.LoadPluginDir
  ClearErrors
  FileOpen \$filePluginDir "\$INSTDIR\\PluginDir.txt" r
  IfErrors done
  FileRead \$filePluginDir \$pluginDir
  FileClose \$filePluginDir
  done:
FunctionEnd
EOH

makensis $SETUP_NSI
