#!/bin/bash

DIR=/tmp/inspect1_$$

mkdir $DIR
smwavset init $DIR/inst.smset

NOTE=60
for FILE in "$@"
do
  smwavset add $DIR/inst.smset $NOTE "$FILE"
  NOTE=$((NOTE + 1))
done
smwavset -d $DIR encode $DIR/inst.smset $DIR/inst_e.smset
smwavset -d $DIR link $DIR/inst_e.smset
echo "smset_dir /" > $DIR/inst_e.smindex
echo "smset $DIR/inst_e.smset" >> $DIR/inst_e.smindex
sminspector $DIR/inst_e.smindex
