.TH "SMINSPECTOR" "1" "2011\-07\-19" "Revision 577" "sminspector Manual Page"

.SH NAME

sminspector - program to visualize contents of SpectMorph instruments

.SH SYNOPSIS

\fBsminspector\fR \fI[OPTIONS]\fR \fISMIndex-File\fR

.SH DESCRIPTION

sminspector is a gui application which can be used to visualize SpectMorph models. An input file with containing a
list of instruments to open should be passed as first argument. This file is a text file, consisting of the commands listed below, and specifies a set of instruments to work with.

.SH INDEX FILE COMMANDS
.TP
\fBsmset_dir\fR "\fIdirectory\fR"
Set directory which contains the smset files.
.PP
.TP
\fBsmset\fR "\fIinstrument.smset\fR"
Add smset-instrument.
.PP

.SH SEE ALSO

smenc.1 <https://testbit.eu/wiki/Smenc.1>, smvisualize.1 <https://testbit.eu/wiki/Smvisualize.1>

