.\" generator: doxer.py 0.6
.\" generation: 2010\-12\-31T11:16:27
.TH "sminspector" "1" "Wed Apr 19 00:50:37 2006" "spectmorph\-0.1.2" "sminspector Manual Page"

.SH
NAME


.PP
sminspector \- Program to display time/frequency plots for SpectMorph models
.SH
SYNOPSIS


.PP
\fBsminspector\fP [\fIOPTIONS\fP] \fISMIndex\-File\fP
.SH
DESCRIPTION


.PP
\fBsminspector\fP is a gui application which can be used to visualize
SpectMorph models. An input file with containing a list of instruments
to open should be passed as first argument. This file is a text file,
consisting of the commands listed below, and specifies a set of
instruments to work with.
.SH
INDEX FILE COMMANDS


.PP




.TP
\fBsmset_dir\fP "\fIdirectory\fP" 
.br
Set directory which contains the smset files.

.TP
\fBsmset\fP "\fIinstrument.smset\fP" 
.br
Add smset\-instrument.

.PP


.SH
SEE ALSO


.PP
smenc(1),
smvisualize(1),
SpectMorph Website (http://space.twc.de/~stefan/spectmorph.php)
