.\" generator: doxer.py 0.6
.\" generation: 2010-06-16T13:20:56
.TH "smplay" "1" "Wed Apr 19 00:50:37 2006" "spectmorph-0.0.3" "smplay Manual Page"

.SH
NAME


.PP
smplay - Program to play a SpectMorph model
.SH
SYNOPSIS


.PP
\fBsmplay\fP [\fIOPTIONS\fP] \fISM-File\fP
.SH
DESCRIPTION


.PP
\fBsmplay\fP is a command line based player for SpectMorph models
(which can be created using \fBsmenc\fP). Playing can use the audio card,
so that the model will be heard directly, or create a wav file instead
if the \fB--export\fP option is used. Since the SpectMorph model consists
of sine waves and noise, options to disable one of these components exist.
.SH
OPTIONS


.PP
\fBsmplay\fP follows the usual GNU command line syntax, with long options starting with two dashes ('-').
.br

.br



.TP
\fB-h\fP, \fB--help\fP 
.br
Shows a brief help message.

.TP
\fB-v\fP, \fB--version\fP 
.br
Prints out \fBbeast\fP and component versions and file paths.

.TP
\fB--rate\fP \fI<sampling rate>\fP 
.br
Set replay rate manually; also useful for specifying the desired rate of
the wav file, if --export is used.

.TP
\fB--no-noise\fP 
.br
Disable noise decoder, so that only the sine wave part of the signal is
decoded.

.TP
\fB--no-sines\fP 
.br
Disable sine decoder, so that only the noise part of the signal is decoded.

.TP
\fB--export\fP \fI<wav filename>\fP 
.br
Instead of playing the file, write the output to a wav file.

.PP


.SH
SEE ALSO


.PP
smenc(1),
SpectMorph Website (http://space.twc.de/~stefan/spectmorph.php)
