.TH "SMSFIMPORT" "1" "2011\-07\-20" "Revision 583" "smsfimport Manual Page"

.SH NAME

smsfimport - program to create SpectMorph models from SoundFont presets

.SH SYNOPSIS

\fBsmsfimport\fR \fI<command>\fR \fI<SoundFontFile>\fR [\fIOPTIONS\fR] [\fI<command specific args>...\fR]

.SH DESCRIPTION

\fBsmsfimport\fR can be used to convert SoundFont presets (.sf2 format) to SpectMorph instruments (.smset format). Since it does not implement all of the functionality provided by SoundFonts, the resulting files can sound different than the original SoundFont, and in some cases the import will fail completely.

.SH OPTIONS

\fBsmsfimport\fR follows the usual GNU command line syntax, with long options starting with two dashes ('-').
.TP
\fB-h\fR, \fB--help\fR
Shows a brief help message.
.PP
.TP
\fB-v\fR, \fB--version\fR
Prints out smsfimport version.
.PP

.SH COMMANDS
.TP
\fBlist\fR \fI<SoundFontFile>\fR
Shows all presets contained in the SoundFontFile.
.PP
.TP
\fBdump\fR \fI<SoundFontFile>\fR [ \fI<PresetName>\fR ]
Displays a detailed view of the parameters specified for a preset (or for all presets).
.PP
.TP
\fBimport\fR \fI<SoundFontFile>\fR \fI<PresetName>\fR
Imports a preset, creating a *.smset file. For preset "Grand Piano", the resulting output would be "grand_piano.smset".
.PP

.SH SEE ALSO

smenc.1 <http://testbit.eu/Smenc.1>, smplay.1 <http://testbit.eu/Smplay.1>

