.TH "SMSTRIP" "1" "2011\-07\-19" "Revision 572" "smstrip Manual Page"

.SH NAME

smstrip - program to remove extra data from SpectMorph model files

.SH SYNOPSIS

\fBsmstrip\fR \fISM-File...\fR

.SH DESCRIPTION

\fBsmstrip\fR is a tool which removes all debugging data from a SpectMorph model.
By default, smenc includes more data than is required for playback in the SM-File.
This extra data can be removed, thereby shrinking the file size considerably.
Note that stripped models can be created directly by the encoder using \fBsmenc -s\fR.

.SH OPTIONS

\fBsmstrip\fR follows the usual GNU command line syntax, with long options starting with two dashes ('-').
.TP
\fB-h\fR, \fB--help\fR
Shows a brief help message.
.PP
.TP
\fB-v\fR, \fB--version\fR
Prints out \fBsmstrip\fR version.
.PP
.TP
\fB--keep-samples\fR
Strips debugging information, but keeps the original sample data (useful for quality comparisions). This of course reduces the file size less than full stripping.
.PP


.br

.SH SEE ALSO

smenc.1 <https://testbit.eu/wiki/Smenc.1>,
smplay.1 <https://testbit.eu/wiki/Smplay.1>

