.\" generator: doxer.py 0.6
.\" generation: 2010\-08\-11T15:06:34
.TH "smstrip" "1" "Wed Apr 19 00:50:37 2006" "spectmorph\-0.1.0" "smstrip Manual Page"

.SH
NAME


.PP
smstrip \- program to remove extra data from SpectMorph model files
.SH
SYNOPSIS


.PP
\fBsmstrip\fP \fISM\-File...\fP
.SH
DESCRIPTION


.PP
\fBsmstrip\fP is a tool which removes all debugging data from a SpectMorph model.
By default, smenc includes more data than is required for playback in the SM\-File.
This extra data can be removed, thereby shrinking the file size considerably. Note
that stripped models can be created directly by the encoder using \fBsmenc \-s\fP.
.SH
OPTIONS


.PP
There are no options. A number of SpectMorph model files can be specified as
command line arguments.
.SH
SEE ALSO


.PP
smenc(1),
smplay(1),
SpectMorph Website (http://space.twc.de/~stefan/spectmorph.php)
