.TH "SMVISUALIZE" "1" "2011\-07\-20" "Revision 587" "smvisualize Manual Page"

.SH NAME

smvisualize - program to visualize a SpectMorph model by displaying its contents as PNG image

.SH SYNOPSIS

\fBsmvisualize\fR \fI<SM-File>\fR \fI<PNG-File>\fR [ \fBdb\fR ]

.SH DESCRIPTION

\fBsmvisualize\fR displays the contents of a SpectMorph model as PNG image. The contents of the spectrum (original FFT results) will be displayed, with time being drawn from left to right, and frequencies being drawn from top (high frequencies) to bottom (low frequencies). There are two modes, one uses db scaling of the intensity, and is activated by using db as last argument, and the other uses linear scaling.

The red dots (and red lines) correspond to the detected sine frequencies.

.SH OPTIONS

smvisualize can me used with two arguments; in this case the first argument is the SpectMorph model, and the second is the PNG file. An optional third argument can be "db". In this case the spectrum intensity will be plotted using a db scale. This is the more natural mode.

.SH SEE ALSO

smenc.1 <https://testbit.eu/wiki/Smenc.1>,
sminspector.1 <https://testbit.eu/wiki/Sminspector.1>

