.TH "SMWAVSET" "1" "2011\-07\-20" "Revision 591" "smwavset Manual Page"

.SH NAME

smwavset - Program to manage spectmorph multiwave files

.SH SYNOPSIS

\fBsmwavset\fR \fI<command>\fR [\fIOPTIONS\fR] [ \fI<command specific args>...\fR ]

.SH DESCRIPTION

\fBsmwavset\fR is a command line tool to manage multi-wave files for SpectMorph. Ususally, a multi wave file is first initialized (using the \fBinit\fR command), then different wave files are added using the \fBadd\fR command. After this has been done, encoding all waves can be done with one single command, like decoding all waves.

.SH OPTIONS

\fBsmwavset\fR follows the usual GNU command line syntax, with long options starting with two dashes ('-').
.TP
\fB-h\fR, \fB--help\fR
Shows a brief help message.
.PP
.TP
\fB-v\fR, \fB--version\fR
Prints out smwavset version.
.PP
.TP
\fB--args\fR \fI<arguments>\fR
Specify additional arguments to be passed to smenc/smplay. This could be --args "-O1" for encoding, or --args "--no-sines" for decoding.
.PP
.TP
\fB-d\fR, \fB--data-dir\fR
For encoding/decoding, this sets a data directory where the .wav files or a list of .wav files (or .sm files), it is important that different wavsets store their files in different directories (otherwise they will overwrite wav files that belong to a different wavset). So specifying a proper data directory which is different for each wavset is usually necessary. The default value is /tmp, which is only appropriate for testing; you should ensure that scripts setup a different value.
.PP
.TP
\fB--format\fR \fI<field1>\fR,\fI<field2>\fR,\fI<field3>\fR,...,\fI<fieldN>\fR
Set the output format for the list command.
.PP
.TP
\fB-j\fR \fI<jobs>\fR
Use \fI<jobs>\fR parallel jobs for encoding (for systems with more than one processor).
.PP

.SH COMMANDS
.TP
\fBinit\fR [ \fI<options>\fR ] \fI<wavset>\fR...
Initializes a new wavset; can also initialize more than one wavset specified on the commandline.
.PP
.TP
\fBadd\fR [ \fI<options>\fR ] \fI<wavset>\fR \fI<midi_note>\fR \fI<path>\fR
Adds a wave file to the wavset, where midi_note is the midi note the wave file has been recorded for.
.PP
.TP
\fBlist\fR [ \fI<options>\fR ] \fI<wavset>\fR
Lists the wave files that are contained within the wavset. The output format for the list command can be specified using the format option (comma seperated fields). See FIELDS section for a list of valid fields
.PP
.TP
\fBencode\fR [ \fI<options>\fR ] \fI<wset_filename>\fR \fI<smset_filename>\fR
Encodes a wavset using smenc.
.PP
.TP
\fBdecode\fR [ \fI<options>\fR ] \fI<smset_filename>\fR \fI<wset_filename>\fR
Decodes a wavset using smplay.
.PP
.TP
\fBdelta\fR [ \fI<options>\fR ] \fI<wset_filename1>\fR...\fI<wset_filenameN>\fR
Computes the difference between many wavsets. The differencce between the first and second wavset is the reference which is 100%. The other wavsets are measured against that reference.
.PP
.TP
\fBlink\fR \fI<smset>\fR
This command includes all .sm files that are referred to by the smset in one big file. This is useful as final step when building instruments.
.PP

.SH FIELDS

For the list command, valid fields are:
.TP
\fBmidi-note\fR
Midi note of the audio entry (0-127)
.PP
.TP
\fBchannel\fR
Channel for the audio entry (0 is the first channel)
.PP
.TP
\fBfilename\fR
Filename of the audio entry
.PP
.TP
\fBmin-velocity\fR
Minimum velocity of the audio entry (0-127)
.PP
.TP
\fBmax-velocity\fR
Maximum velocity of the audio entry (0-127)
.PP


.br

.SH SEE ALSO

smenc.1 <https://testbit.eu/wiki/Smenc.1>,
smplay.1 <https://testbit.eu/wiki/Smplay.1>,
smstrip.1 <https://testbit.eu/wiki/Smstrip.1>

