.\" generator: doxer.py 0.6
.\" generation: 2010\-10\-29T18:26:30
.TH "smwavset" "1" "Wed Apr 19 00:50:37 2006" "spectmorph\-0.1.1" "smwavset Manual Page"

.SH
NAME


.PP
smwavset \- Program to manage spectmorph multiwave files
.SH
SYNOPSIS


.PP
\fBsmwavset\fP <command> [\fIOPTIONS\fP] [ \fI<command specific args>...\fP ]
.SH
DESCRIPTION


.PP
\fBsmwavset\fP is a command line tool to manage multi\-wave files for
SpectMorph. Ususally, a multi wave file is first initialized (using the
init command), then different wave files are added using the add command.
After this has been done, encoding all waves can be done with one single
command, like decoding all waves.
.SH
OPTIONS


.PP
\fBsmwavset\fP follows the usual GNU command line syntax, with long options
starting with two dashes ('\-').
.br

.br



.TP
\fB\-h\fP, \fB\-\-help\fP 
.br
Shows a brief help message.

.TP
\fB\-v\fP, \fB\-\-version\fP 
.br
Prints out \fBsmenc\fP version.

.TP
\fB\-\-args\fP \fI<arguments>\fP 
.br
Specify additional arguments to be passed to smenc/smplay. This could
be \-\-args "\-O1" for encoding, or \-\-args "\-\-no\-sines" for decoding.

.TP
\fB\-d\fP, \fB\-\-data\-dir\fP 
.br
For encoding/decoding, this sets a data directory where the .wav files or
.sm files should be stored. Since a wavset is like an index pointing to
a list of .wav files (or .sm files), it is important that different wavsets
store their files in different directories (otherwise they will overwrite
wav files that belong to a different wavset). So specifying a proper data
directory which is different for each wavset is usually necessary. The
default value is /tmp, which is only appropriate for testing; you should
ensure that scripts setup a different value.

.TP
\fB\-\-format\fP \fI<field1>\fP,\fI<field2>\fP,\fI<field3>\fP,...,\fI<fieldN>\fP 
.br
Set the output format for the list command.

.PP


.SH
COMMANDS

.SS
init [ <options> ] <wavset>...


.PP

Initializes a new wavset; can also initialize more than one wavset
specified on the commandline.
.SS
add [ <options> ] <wavset> <midi_note> <path>


.PP

Adds a wave file to the wavset, where midi_note is the midi note the
wave file has been recorded for.
.SS
list [ <options> ] <wavset>


.PP

Lists the wave files that are contained within the wavset. The output
format for the list command can be specified using the format option
(comma seperated fields).
.br

.br
\fBValid fields:\fP



.TP
midi\-note 
.br
Midi note of the audio entry (0\-127) 
.TP
channel 
.br
Channel for the audio entry (0 is the first channel) 
.TP
filename 
.br
Filename of the audio entry 
.TP
min\-velocity 
.br
Minimum velocity of the audio entry (0\-127) 
.TP
max\-velocity 
.br
Maximum velocity of the audio entry (0\-127)

.PP


.SS
encode [ <options> ] <wset_filename> <smset_filename>


.PP

Encodes a wavset using smenc.
.SS
decode [ <options> ] <smset_filename> <wset_filename>


.PP

Decodes a wavset using smplay.
.SS
delta [ <options> ] <wset_filename1>...<wset_filenameN>


.PP

Computes the difference between many wavsets. The differencce between
the first and second wavset is the reference which is 100%. The other
wavsets are measured against that reference.
.SS
link <smset>


.PP

This command includes all .sm files that are referred to by the smset
in one big file. This is useful as final step when building instruments.
.SH
SEE ALSO


.PP
smenc(1),
smplay(1),
smstrip(1),
SpectMorph Website (http://space.twc.de/~stefan/spectmorph.php)
