.TH "SPECTMORPHOSCGUI" "1" "2011\-07\-20" "Revision 592" "spectmorphoscgui Manual Page"

.SH NAME

spectmorphoscgui - helper application for SpectMorph BEAST plugin

.SH SYNOPSIS

\fBspectmorphoscgui\fR \fI<title>\fR

.SH DESCRIPTION

\fBspectmorphoscgui\fR is a helper application which is used by the SpectMorph BEAST plugin to display a gui. It is only useful when called by the BEAST plugin.

.SH OPTIONS

The window title is set by the \fI<title>\fR argument.

.SH SEE ALSO

smjack.1 <https://testbit.eu/wiki/Smjack.1>

